export default [{
  title: 'Fred: Distributed Crawling and Data Ingestion Tool',
  tech_tags: ['AWS EB', 'AWS SQS', 'AWS ECS', 'AWS S3', 'AWS VPC', 'SQL Server', 'Postgres', 'Django', 'VueJS', 'Docker'],
  short_desc: 'Collborating with the complex workflow of AWS dynamic resources, Fred crawls and ingests any scale of data with reasonable speed. From the lowest level of code implementation to the highest level of system architecture, every part of Fred serves to quickly adapt new data manipulation requirements from the company.',
  intro_content: 'https://www.youtube.com/embed/nsrfEcbBOC0?ecver=2',
  intro_type: 'youtube',
  company: 'Myers Media Group LLC',
  roles: ['Solo'],
  supervised_by_architech: true,
  percentage_feature_responsible: 100,
  percentage_code_contribution: 100,
  active_start: '2017/05',
  active_end: '2017/12',
  current_maintainer: true,
  funded: true,
  code_repo: 'Unavailable',
  updated: '2017/12/03',
}, {
  title: 'Rainbow: Multi-source, Multi-destination ETL Tool',
  tech_tags: ['AWS Lambda', 'AWS SimpleWorkflow', 'Docker', 'Vagrant', 'Pandas', 'Django', 'Scrapy', 'Postgres'],
  short_desc: "Since October 2016, Rainbow has been working for my colleagues to ETL jobs from 3 raw data sources to 4 data destinations. With an internal task scheduler built on AWS Lambda and AWS SimpleWorkflow, Rainbow is able to run jobs both on-demand or on schedule. Rainbow also uses Pandas to generate SEO data reports in pdf format, which serves to open up new business with new clients.",
  intro_content: '(Demo will be ready by 2017/12/15)',
  intro_type: 'intro_large',
  company: 'Myers Media Group LLC',
  roles: ['Solo'],
  supervised_by_architech: true,
  percentage_feature_responsible: 98,
  percentage_code_contribution: 95,
  active_start: '2016/08',
  active_end: '2017/02',
  current_maintainer: true,
  funded: true,
  code_repo: 'Unavailable',
  updated: '2017/12/03',
}, {
  title: 'SIC: Internal Website for Sales Management & Data Visualization',
  tech_tags: ['ReactJS', 'GraphQL', 'Docker', 'NodeJS', 'Knex', 'Sequelize', 'Swagger', 'Bookshelf', 'JWT', 'Postgres'],
  short_desc: 'My very first ES2015 project',
  intro_content: null,
  intro_type: 'text',
  company: 'Myers Media Group LLC',
  roles: ['Associate'],
  supervised_by_architech: true,
  percentage_feature_responsible: 10,
  percentage_code_contribution: 10,
  active_start: '2016/09',
  active_end: '2017/01',
  current_maintainer: false,
  funded: true,
  code_repo: 'Unavailable',
  updated: '2017/12/03',
}, {
  title: 'AI Master Website: Pure SPA',
  tech_tags: ['VueJS', 'Webpack', 'Sass', 'Docker', 'Swagger', 'NodeJS', 'Sequelize', 'Postgres', 'JWT', 'AWS S3', 'Aliyun'],
  short_desc: 'Powered by VueJS, ai-master.com is a pure single page application suitable for very quick navigation. All compiled static content is loaded at the beginning. Because we strictly follow design principles and VueJS best practices, the project is highly maintainable and extensible.',
  intro_content: 'Demo: <a href="https://ai-master.com">ai-master.com</a>',
  intro_type: 'intro_large',
  company: 'AI Master Inc.',
  roles: ['Associate', 'Technical Director'],
  supervised_by_architech: false,
  percentage_feature_responsible: 90,
  percentage_code_contribution: 25,
  active_start: '2017/03',
  active_end: '2017/09',
  current_maintainer: true,
  funded: true,
  code_repo: 'Unavailable',
  updated: '2017/12/03',
}, {
  title: 'AI Book: Interactive Textbook with Modulized Content',
  tech_tags: ['VueJS', 'Sass', 'Docker', 'Swagger', 'NodeJS', 'Sequelize', 'Postgres'],
  short_desc: 'A comprehensive and attractive interactive textbook may have many courses, and a course may have many chapters. A chapter has sections, under which there are paragraphs, animations, etc. AI Book is a solution that displays this content of tree-like structure, and also allows user interations like taking quizes and exams.',
  intro_content: 'Demo: <a href="https://ai-master.com/course/3">Read the textbook here</a>',
  intro_type: 'intro_large',
  company: 'AI Master Inc.',
  roles: ['Technical Director'],
  supervised_by_architech: false,
  percentage_feature_responsible: 50,
  percentage_code_contribution: 40,
  active_start: '2017/06',
  active_end: '2017/09',
  current_maintainer: true,
  funded: true,
  code_repo: 'Unavailable',
  updated: '2017/12/03',
}, {
  title: 'AI Book Content Editor: Tree Structure Content Editor',
  tech_tags: ['VueJS', 'Docker', 'Swagger', 'NodeJS', 'Sequelize', 'Postgres'],
  short_desc: 'This is the tool that builds every AI Master interactive textbook. Utilizing the ElementUI library of VueJS and advanced features of Vuex, it contains only 7 core files with <1500 lines of javascript code to express its powerful functions.',
  intro_content: 'https://www.youtube.com/embed/GVdm1kt9skk?ecver=2',
  intro_type: 'youtube',
  company: 'AI Master Inc.',
  roles: ['Solo'],
  supervised_by_architech: false,
  percentage_feature_responsible: 100,
  percentage_code_contribution: 100,
  active_start: '2017/07',
  active_end: '2017/08',
  current_maintainer: true,
  funded: true,
  code_repo: 'Unavailable',
  updated: '2017/12/03',
}]